// DRAFT assignment of traits to the 81 generals (design/content/general-traits-draft.md). Lab data only.
// Rule traits: delayer, rally, master_of_ground, scouts. At most one per general, except Hannibal.
export const GENERAL_TRAITS: Record<string, { traits: string[]; why: string }> = {
  // Macedon & Successors
  philip2: { traits: ["hammer_and_anvil", "oblique_order"], why: "Built the phalanx-and-Companions army; Chaeronea's refused flank" },
  alexander: { traits: ["oblique_order", "hammer_and_anvil", "rally"], why: "Led the decisive wedge himself at Issus and Gaugamela; his presence turned wavering lines" },
  parmenion: { traits: ["steady"], why: "Held the left at Gaugamela while Alexander won the battle" },
  antigonus1: { traits: ["hammer_and_anvil"], why: "Paraetacene and Gabiene: Macedonian combined arms at full scale" },
  eumenes: { traits: ["mercenary_captain", "scouts"], why: "A Greek secretary commanding Macedonians; out-manoeuvred Antigonus by deception" },
  seleucus1: { traits: ["terror"], why: "Four hundred elephants decided Ipsus" },
  ptolemy1: { traits: ["steady"], why: "Gaza 312: a prepared line that stopped Demetrius's elephants" },
  demetrius: { traits: ["furor"], why: "Brilliant and erratic; his cavalry won its wing at Ipsus and rode off the field" },
  lysimachus: { traits: [], why: "" },
  craterus: { traits: ["steady"], why: "Alexander's infantry commander, beloved of the phalanx" },
  pyrrhus: { traits: ["terror", "rally"], why: "Elephants the Romans had never seen; fought in the front rank at Heraclea and Asculum" },
  antigonus3: { traits: [], why: "" },
  philip5: { traits: [], why: "" },
  antiochus3: { traits: ["numbers"], why: "Raphia and the anabasis: the great eastern levy" },
  // Greek city-states
  xenophon: { traits: ["mercenary_captain", "master_of_ground"], why: "Brought ten thousand mercenaries home across the Armenian mountains" },
  agesilaus: { traits: ["steady"], why: "Spartan discipline at Coronea" },
  iphicrates: { traits: ["harass", "mercenary_captain"], why: "His mercenary peltasts destroyed a Spartan regiment at Lechaeum" },
  chabrias: { traits: ["steady"], why: "Ordered his hoplites to kneel and hold; Agesilaus declined to attack" },
  epaminondas: { traits: ["oblique_order", "deep_ranks"], why: "Leuctra: the left wing fifty shields deep, the right refused" },
  pelopidas: { traits: ["furor"], why: "The Sacred Band as a shock force; Tegyra" },
  dionysius1: { traits: ["mercenary_captain"], why: "A tyrant's army of hired Greeks, Iberians and Campanians" },
  timoleon: { traits: ["master_of_ground"], why: "Crimissus: struck the Carthaginians as they crossed a river in a storm" },
  agathocles: { traits: [], why: "" },
  agis3: { traits: [], why: "" },
  cleomenes3: { traits: [], why: "" },
  philopoemen: { traits: ["envelopment", "master_of_ground"], why: "Plutarch: he studied ground obsessively; his cavalry decided Sellasia" },
  // Achaemenid Persia
  artaxerxes2: { traits: ["numbers"], why: "Cunaxa: the royal levy" },
  pharnabazus: { traits: ["harass"], why: "His cavalry harried Agesilaus across Phrygia" },
  memnon: { traits: ["delayer", "mercenary_captain"], why: "Urged scorched earth against Alexander; commanded the Greek mercenaries" },
  darius3: { traits: ["numbers"], why: "Issus and Gaugamela" },
  mazaeus: { traits: ["envelopment"], why: "His cavalry nearly broke Parmenion's wing at Gaugamela" },
  bessus: { traits: [], why: "" },
  ariobarzanes: { traits: ["master_of_ground"], why: "Held the Persian Gates for a month" },
  // Carthage
  himilco: { traits: [], why: "" },
  hamilcar: { traits: ["mercenary_captain", "harass"], why: "Years of raiding from Mount Eryx; then put down his own mercenaries" },
  xanthippus: { traits: ["terror", "envelopment"], why: "Bagradas: elephants through the center, cavalry around both flanks" },
  hasdrubal_f: { traits: [], why: "" },
  hannibal: { traits: ["envelopment", "scouts", "master_of_ground"], why: "Cannae, Trasimene, the Alps" },
  hasdrubal_b: { traits: [], why: "" },
  mago: { traits: ["envelopment"], why: "Sprang the ambush at the Trebia" },
  hasdrubal_g: { traits: [], why: "" },
  maharbal: { traits: ["harass"], why: "Commander of the Numidian horse" },
  // Rome
  camillus: { traits: ["deep_ranks", "rally"], why: "Credited with the manipular reforms; second founder of Rome after the Allia" },
  papirius: { traits: ["steady"], why: "Cursor, the disciplinarian of the Samnite wars" },
  rullianus: { traits: ["deep_ranks"], why: "Sentinum: held his reserves until the Samnites tired" },
  dentatus: { traits: ["steady"], why: "Stood against Pyrrhus's elephants at Beneventum" },
  regulus: { traits: [], why: "" },
  flaminius: { traits: [], why: "" },
  fabius: { traits: ["delayer", "steady"], why: "The Delayer" },
  paullus: { traits: [], why: "" },
  marcellus: { traits: ["rally", "furor"], why: "The Sword of Rome: beaten by Hannibal one day, back in the field the next; killed a Gallic king in single combat" },
  nero: { traits: ["envelopment"], why: "Metaurus: marched his wing behind the army to fall on the Carthaginian flank" },
  scipio_sr: { traits: [], why: "" },
  scipio: { traits: ["envelopment", "scouts", "deep_ranks"], why: "Ilipa's reversed line and double envelopment; the lanes and reserves at Zama" },
  // Warring States China
  wuqi: { traits: ["steady", "volley"], why: "The Wei Wuzu: picked, drilled heavy infantry; never beaten, by tradition" },
  sunbin: { traits: ["scouts", "volley"], why: "Maling: ten thousand crossbows waiting in the dusk" },
  pangjuan: { traits: [], why: "" },
  wuling: { traits: ["harass"], why: "Put Zhao in nomad dress and on horseback with bows" },
  yueyi: { traits: ["mercenary_captain"], why: "Led a five-state coalition army into Qi" },
  tiandan: { traits: ["terror"], why: "The fire-oxen of Jimo" },
  baiqi: { traits: ["envelopment", "terror", "numbers"], why: "Changping: an army encircled and destroyed; a name that emptied cities" },
  lianpo: { traits: ["delayer", "steady"], why: "Held Changping by refusing battle, until he was replaced" },
  limu: { traits: ["volley", "envelopment"], why: "Feigned weakness for years, then enveloped the Xiongnu with massed archers and chariots" },
  wangjian: { traits: ["numbers", "delayer"], why: "Demanded six hundred thousand men for Chu, then waited a year for Chu to tire" },
  mengtian: { traits: ["volley"], why: "Crossbows against the Xiongnu in the Ordos" },
  xiangyu: { traits: ["furor", "rally"], why: "Broke the cauldrons and sank the boats at Julu" },
  hanxin: { traits: ["numbers", "envelopment", "scouts"], why: "'The more the better'; repaired the plank roads in the open and marched by Chencang" },
  // Steppe
  ateas: { traits: ["harass"], why: "Scythian horse archers" },
  spitamenes: { traits: ["harass", "envelopment"], why: "Polytimetus: feigned flight, then a ring of horse archers around a Macedonian column" },
  arsaces1: { traits: ["harass"], why: "The Parni on horseback" },
  // India
  porus: { traits: ["terror"], why: "The elephant line at the Hydaspes" },
  chandragupta: { traits: ["numbers", "terror"], why: "Six hundred thousand foot and nine thousand elephants, by Greek report" },
  bindusara: { traits: [], why: "" },
  ashoka: { traits: ["numbers"], why: "Kalinga" },
  // Gauls & Celts
  brennus1: { traits: ["furor", "terror"], why: "The Allia: the Roman line broke at the first rush" },
  britomaris: { traits: [], why: "" },
  brennus2: { traits: ["furor"], why: "The great raid on Greece" },
  bolgios: { traits: [], why: "" },
  aneroestes: { traits: ["furor"], why: "Led the Gaesatae at Telamon" },
  concolitanus: { traits: [], why: "" },
  viridomarus: { traits: ["furor"], why: "Rode out to single combat at Clastidium" },
};
